// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9QLPz_ZIp6CBWfBoLC_BFsisZE2rqqs',
    appId: '1:486242738202:web:33115fb7aac4e2a77771a3',
    messagingSenderId: '486242738202',
    projectId: 'toko-olahraga-55233',
    authDomain: 'toko-olahraga-55233.firebaseapp.com',
    storageBucket: 'toko-olahraga-55233.firebasestorage.app',
    measurementId: 'G-45LY62QJTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoIfcR9e7pVU5vgCFjyYbE_PpFMp3Gko',
    appId: '1:486242738202:android:46998e2b655f8f8b7771a3',
    messagingSenderId: '486242738202',
    projectId: 'toko-olahraga-55233',
    storageBucket: 'toko-olahraga-55233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrPTs3PX6_xA-yteg-oCJSZctLiPC9kU',
    appId: '1:486242738202:ios:bca7f55f9935f3137771a3',
    messagingSenderId: '486242738202',
    projectId: 'toko-olahraga-55233',
    storageBucket: 'toko-olahraga-55233.firebasestorage.app',
    iosBundleId: 'com.example.tokoOlahraga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL9QLPz_ZIp6CBWfBoLC_BFsisZE2rqqs',
    appId: '1:486242738202:web:a13dcb96ceca19907771a3',
    messagingSenderId: '486242738202',
    projectId: 'toko-olahraga-55233',
    authDomain: 'toko-olahraga-55233.firebaseapp.com',
    storageBucket: 'toko-olahraga-55233.firebasestorage.app',
    measurementId: 'G-LSB00EFQGF',
  );
}
